name: TEST JOB
on: 
    workflow_dispatch:
jobs:
  Test_job:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.CR_PAT }}
            -   name: print variables
                shell: bash
                run: |
                    echo "${{ github.repository }}"
                    echo "${{ github.sha }}"
                    echo "${{ github.repository_owner }}"
                    echo "${{ github.run_id }}"
